---
development:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
<<<<<<< HEAD

=======
  enhance_image_tag: true
  static_file_support: false
>>>>>>> 45f1ff10c2b2e577515f602e43d41f645e4d9012
production:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
<<<<<<< HEAD

=======
  enhance_image_tag: true
  static_file_support: true
>>>>>>> 45f1ff10c2b2e577515f602e43d41f645e4d9012
test:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
<<<<<<< HEAD
=======
  enhance_image_tag: true
  static_file_support: false
>>>>>>> 45f1ff10c2b2e577515f602e43d41f645e4d9012
